//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public Dashboard()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int id { get; set; }
        public int Id { get; internal set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public string E_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
