//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foodtable
    {
        public Foodtable()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int Food_id { get; set; }
        public string Food_name { get; set; }
        public int Food_price { get; set; }
        public int Food_Qty { get; set; }
    
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
