//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int id { get; set; }
        public int Foodid { get; set; }
        public int OrderId { get; set; }
        public int Unitprice { get; set; }
        public int Qty { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual Foodtable Foodtable { get; set; }
    }
}
